//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuidGeneratorClient.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/WCFServiceWebRole")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IGuidGeneratorService")]
    public interface IGuidGeneratorService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGuidGeneratorService/Generate", ReplyAction="http://tempuri.org/IGuidGeneratorService/GenerateResponse")]
        string Generate();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGuidGeneratorService/Generate", ReplyAction="http://tempuri.org/IGuidGeneratorService/GenerateResponse")]
        System.Threading.Tasks.Task<string> GenerateAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGuidGeneratorService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IGuidGeneratorService/GetDataUsingDataContractResponse")]
        GuidGeneratorClient.ServiceReference1.CompositeType GetDataUsingDataContract(GuidGeneratorClient.ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGuidGeneratorService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IGuidGeneratorService/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<GuidGeneratorClient.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(GuidGeneratorClient.ServiceReference1.CompositeType composite);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGuidGeneratorServiceChannel : GuidGeneratorClient.ServiceReference1.IGuidGeneratorService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GuidGeneratorServiceClient : System.ServiceModel.ClientBase<GuidGeneratorClient.ServiceReference1.IGuidGeneratorService>, GuidGeneratorClient.ServiceReference1.IGuidGeneratorService {
        
        public GuidGeneratorServiceClient() {
        }
        
        public GuidGeneratorServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GuidGeneratorServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GuidGeneratorServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GuidGeneratorServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Generate() {
            return base.Channel.Generate();
        }
        
        public System.Threading.Tasks.Task<string> GenerateAsync() {
            return base.Channel.GenerateAsync();
        }
        
        public GuidGeneratorClient.ServiceReference1.CompositeType GetDataUsingDataContract(GuidGeneratorClient.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<GuidGeneratorClient.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(GuidGeneratorClient.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
    }
}
